Upgrade flutter to 3.19
thetribeio/generator-project pull request #1729
Opened 2024-05-14 07:04 UTC by micklenormand

2024-05-16 09:11 UTC, jvasseur requested changes

2024-05-16 09:11 UTC, jvasseur commented on generators/flutter-mobile/templates/base/ios/Runner.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.example.myapp;
Why removing the tempalted vars here ?

2024-05-16 09:11 UTC, jvasseur commented on generators/flutter-mobile/templates/base/ios/Runner.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.example.myapp;
Same here.

2024-05-17 08:27 UTC, micklenormand commented on generators/flutter-mobile/templates/base/ios/Runner.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.example.myapp;
fixed :-)

2024-05-17 08:27 UTC, micklenormand commented on generators/flutter-mobile/templates/base/ios/Runner.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.example.myapp;
fixed :-)

2024-05-17 08:27 UTC, micklenormand commented on generators/flutter-mobile/templates/base/ios/Runner.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.example.myapp;
fixed :-)

2024-05-17 12:44 UTC, merged